### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [MikkelSnitker/heylink-gtm#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation url [https://heylink.com/gtm/documentation](https://heylink.com/gtm/documentation) mentioned in the manifest file is not valid. It shows "404 Page not found error". 

![image](https://user-images.githubusercontent.com/53495700/93931710-02e43d00-fcd4-11ea-92eb-24b9ad40efde.png)

2) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on "orderid" and "amount" when generating the url
const url = 'https://trackha.heylink.com/aff_l?offer_id=12&adv_sub='+orderid+'&amount='+amount;

**Comment by MikkelSnitker** [comment]
I have fixed the issues, should I re-submit the template?
